version: '3.3'

services:
  gcal-agenda:
    container_name: gcal-agenda
    build: .
    environment:
      weather_api_key: ${weather_api_key}
      font_wesome_kit_id: ${font_wesome_kit_id}
      latitude: ${latitude}
      longitude: ${longitude}
      TZ: Asia/Bangkok
    ports:
      - "8921:80"

# use system's cronjob
## */1 * * * * docker exec -t gcal-agenda python3 create_html.py
